name: CI
run-name: CI Run
on: [push]
jobs:
  unit-test: 
    name: Unit tests
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: setup
        run: make setup
      - name: py-test
        run: make py-test
  static-type: 
    name: Static typing
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: setup
        run: make setup
      - name: py-static
        run: make py-static
    
