name: CI
run-name: CI Run
on: [push]
jobs:
  unit-test: 
    name: Unit tests
    runs-on: ubuntu-latest
    steps: 
      - name: py-test
        run: make setup; make py-test
  static-type: 
    name: Static typing
    runs-on: ubuntu-latest
    steps: 
      - name: py-static
        run: make setup; make py-static
    
